[project]
name = "utxoracle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "marimo>=0.13.10",
    "matplotlib>=3.10.3",
    "paramiko>=3.5.1",
    "polars>=1.29.0",
    "pyarrow>=20.0.0",
]
